// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: model/add_metric_responce.proto

package model

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMetricResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric *Metric `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Error  *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // ошибка
}

func (x *AddMetricResponce) Reset() {
	*x = AddMetricResponce{}
	mi := &file_model_add_metric_responce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricResponce) ProtoMessage() {}

func (x *AddMetricResponce) ProtoReflect() protoreflect.Message {
	mi := &file_model_add_metric_responce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricResponce.ProtoReflect.Descriptor instead.
func (*AddMetricResponce) Descriptor() ([]byte, []int) {
	return file_model_add_metric_responce_proto_rawDescGZIP(), []int{0}
}

func (x *AddMetricResponce) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *AddMetricResponce) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_model_add_metric_responce_proto protoreflect.FileDescriptor

var file_model_add_metric_responce_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x64, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x26, 0x67, 0x6f, 0x2e, 0x6d, 0x75, 0x73, 0x74, 0x68, 0x61, 0x76, 0x65, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01,
	0x0a, 0x11, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x75, 0x73, 0x74, 0x68, 0x61, 0x76,
	0x65, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41,
	0x6e, 0x74, 0x6f, 0x6e, 0x42, 0x65, 0x7a, 0x65, 0x6d, 0x73, 0x6b, 0x69, 0x79, 0x2f, 0x67, 0x6f,
	0x2d, 0x6d, 0x75, 0x73, 0x74, 0x68, 0x61, 0x76, 0x65, 0x2d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_add_metric_responce_proto_rawDescOnce sync.Once
	file_model_add_metric_responce_proto_rawDescData = file_model_add_metric_responce_proto_rawDesc
)

func file_model_add_metric_responce_proto_rawDescGZIP() []byte {
	file_model_add_metric_responce_proto_rawDescOnce.Do(func() {
		file_model_add_metric_responce_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_add_metric_responce_proto_rawDescData)
	})
	return file_model_add_metric_responce_proto_rawDescData
}

var file_model_add_metric_responce_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_add_metric_responce_proto_goTypes = []any{
	(*AddMetricResponce)(nil), // 0: go.musthave.metrics.grpc.service.model.AddMetricResponce
	(*Metric)(nil),            // 1: go.musthave.metrics.grpc.service.model.Metric
}
var file_model_add_metric_responce_proto_depIdxs = []int32{
	1, // 0: go.musthave.metrics.grpc.service.model.AddMetricResponce.metric:type_name -> go.musthave.metrics.grpc.service.model.Metric
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_add_metric_responce_proto_init() }
func file_model_add_metric_responce_proto_init() {
	if File_model_add_metric_responce_proto != nil {
		return
	}
	file_model_metric_proto_init()
	file_model_add_metric_responce_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_add_metric_responce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_add_metric_responce_proto_goTypes,
		DependencyIndexes: file_model_add_metric_responce_proto_depIdxs,
		MessageInfos:      file_model_add_metric_responce_proto_msgTypes,
	}.Build()
	File_model_add_metric_responce_proto = out.File
	file_model_add_metric_responce_proto_rawDesc = nil
	file_model_add_metric_responce_proto_goTypes = nil
	file_model_add_metric_responce_proto_depIdxs = nil
}
